language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - pip install -v 'travis-cargo<0.2' --user
  - travis-cargo --only nightly install rustfmt-nightly -- --force

script:
  - |
      travis-cargo --only nighlty fmt -- --write-mode=diff &&
      cargo build --release --no-default-features &&
      cargo build --release --all-features &&
      cargo test --release --all-features &&
      travis-cargo --only stable doc -- --features "from_url validation serde"

after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
