[package]
name = "rss"
version = "0.6.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>", "Corey Farwell <coreyf@rwell.org>", "Chris Palmer <pennstate5013@gmail.com>"]
description = "Library for serializing the RSS web content syndication format"
repository = "https://github.com/rust-syndication/rss"
documentation = "https://docs.rs/rss/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["rss", "feed", "parser", "parsing"]
include = ["src/*", "Cargo.toml", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]

[features]
from_url = ["reqwest"]

[dependencies]
quick-xml = "0.7.3"
chrono = "0.3"
url = "1.4"
mime = "0.2"
mailchecker = "3.0"
reqwest = { version = "0.6", optional = true }
