[package]
name = "rss"
version = "1.8.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>", "Corey Farwell <coreyf@rwell.org>", "Chris Palmer <pennstate5013@gmail.com>"]
description = "Library for serializing the RSS web content syndication format"
repository = "https://github.com/rust-syndication/rss"
documentation = "https://docs.rs/rss/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["rss", "feed", "parser", "parsing"]
include = ["src/*", "Cargo.toml", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]

[package.metadata.docs.rs]
all-features = false

[features]
from_url = ["reqwest"]
validation = ["chrono", "url", "mime"]

[dependencies]
failure = "0.1"
quick-xml = "0.15"
derive_builder = "0.7"
chrono = {version = "0.4", optional = true }
url = { version = "1.7", optional = true }
mime = { version = "0.3", optional = true }
reqwest = { version = "0.9", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
