name: Coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        use-tool-cache: true
    - name: Measure coverage
      run: |
        cargo tarpaulin \
          --forward \
          --timeout 5 \
          --run-types Tests Doctests \
          --all-features \
          --out Xml \
          --verbose \
          -- \
          --test-threads=1
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
